modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/theomenden/ConfigurableBossBars/issues"
license = "MIT"

[[mods]]
modId = "configurablebossbars"
version = "${file.jarVersion}"
displayName = "Wandering Cocoa"
authors = "Alu"
description = '''
A simple fabric mod to allow for configurations of boss bars
'''
logoFile = "icon.png"

[[dependencies.configurablebossbars]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.configurablebossbars]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.configurablebossbars]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.configurablebossbars]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "configurablebossbars.mixins.json"

[[mc-publish]]
modrinth="iB0MlSms"
curseforge=915450